all: retro_exec2

retro_help:
	@echo "Ejecucion algoritmo perceptron multicapa: (python3 main.py -h para ayuda general)"
	@ python3 main.py -h

retro_exec2:
	python3 main.py ../data/problema_real1.txt 1 5 --tam_train 0.8

retro_exec6:
	python3 main.py ../data/problema_real6.txt 2 20 --tam_train 0.7 --nepocas 5000
make:
