all: retro_exec2

retro_help:
	@echo "Ejecucion algoritmo perceptron multicapa: (python3 main.py -h para ayuda general)"
	@echo #TODO "python3 main.py nombre_del_fichero_entrenamiento modo [--in_file2 nombre_del_fichero_test] [--out_file nombre_del_fichero_salida] [--tam_train porcentaje_train] [--umbral umbral] [--alpha alpha] [--nepocas max_epocas_entrenamiento]"

retro_exec2:
	#TODO python3 main.py per data/problema_real2.txt 1 --umbral 0.5 --alpha 0.1 --tam_train 0.8 --nepocas 500

retro_exec6:
	#TODO python3 main.py ada data/problema_real2.txt 1 --tol 0.1 --alpha 0.1

make: