all: retro_exec2

retro_help:
	@echo "Ejecucion algoritmo perceptron multicapa: (python3 main.py -h para ayuda general)"
	@ python3 main.py -h

retro_exec2:
	python3 main.py '../data/problema_real2.txt' 1 3 3 3 


retro_exec6:
	python3 main.py '../data/problema_real6.txt' 1 20 --tam_train 0.7 --alpha 0.1 --norm estandar --nepocas 5000
make:

